import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'



export default function Home({results}) {
  console.log(results)
  return (
    <div>
      <Head>
        <title>Hulu 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
           {/* header  */}
           <Header/>
           {/* nav  */}
           <Nav/>
           {/* results  */}
           <Results  results={results}  />

      </main>

      
    </div>
  )
}

export async function getServerSideProps(context){
  const genre=context.query.genre;
   const request=await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
   .then((res)=>{
      return res.json()
   })

  return {
    props:{
      results:request.results
    }
  }

}
